"""auto-votesal

Revision ID: 0b03d6fa8e4e
Revises: 0de9f8e5c1a1
Create Date: 2022-08-26 18:14:18.671249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b03d6fa8e4e'
down_revision = '0de9f8e5c1a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votesal',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['postsal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['usersal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # op.add_column('postsal', sa.Column('create_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # op.drop_column('postsal', 'created_at')
    # op.add_column('usersal', sa.Column('create_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # op.drop_column('usersal', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('usersal', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.drop_column('usersal', 'create_at')
    # op.add_column('postsal', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # op.drop_column('postsal', 'create_at')
    op.drop_table('votesal')
    # ### end Alembic commands ###
