"""add phone_number

Revision ID: aa6cfd7e73ca
Revises: 0b03d6fa8e4e
Create Date: 2022-08-26 18:30:03.136612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa6cfd7e73ca'
down_revision = '0b03d6fa8e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersal', sa.Column('phone_number', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersal', 'phone_number')
    
    # ### end Alembic commands ###
